### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Addibro** [ricardofbarros/linter-js-standard#102]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.3.0

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/Andreas/.atom/packages/linter-js-standard/lib/utils/select-style.js:40

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at getStyleThroughDevDeps (/Users/Andreas/.atom/packages/linter-js-standard/lib/utils/select-style.js:40:42)
    at selectStyle (/Users/Andreas/.atom/packages/linter-js-standard/lib/utils/select-style.js:74:12)
    at Object.module.exports.__cacheTextEditor (/Users/Andreas/.atom/packages/linter-js-standard/lib/init.js:92:17)
    at storeSettings (/Users/Andreas/.atom/packages/linter-js-standard/lib/init.js:64:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:203:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:344:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:702:15)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:214:21)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
  3x -2:47.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:38.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:38 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:37.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:31.4.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:26 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:20.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:19.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:17.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:12.7.0 core:backspace (atom-text-editor.editor.is-focused)
 14x -1:55.6.0 core:move-right (atom-text-editor.editor.is-focused)
 17x -1:50.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:46.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:33.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:24.4.0 tabs:split-left (li.tab.sortable.active.right-clicked)
     -1:16.5.0 tabs:split-right (li.tab.sortable.active.right-clicked)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "about"
    ]
  },
  "linter-js-standard": {
    "checkStyleDevDependencies": true
  }
}
```

### Installed Packages

```coffee
# User
file-type-icons, v1.0.1
linter, v1.11.4
linter-js-standard, v3.3.0
minimap, v4.21.0

# Dev
No dev packages
```

**Comment by joshmanders** [comment]
Getting same error when I create new files or try to open one sometimes.

**Comment by SEAPUNK** [comment]
Is the "Check for standard" setting enabled for you both? That was causing the problem for me.

**Comment by amiuhle** [comment]
Getting the same error. "Check for standard" is activated, and the project I'm getting the error doesn't have a `package.json` at all.

**Comment by ricardofbarros** [comment]
Thanks to @JGAntunes PR this issue has been fixed, I have already published a patch version with his fix. Cheers
