### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash._basefor'

### ISSUE THREAD

**Issue by BrentonCozby** [ricardofbarros/linter-js-standard#118]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.3.3
### Stack Trace

Uncaught Error: Cannot find module 'lodash._basefor'

```
At module.js:340

Error: Cannot find module 'lodash._basefor'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BrentonCozby/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules/lodash.merge/node_modules/lodash.isplainobject/index.js:9:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BrentonCozby/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules/lodash.merge/index.js:14:21)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BrentonCozby/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/testers/rule-tester.js:53:13)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BrentonCozby/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/api.js:11:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```
### Commands

```
     -6:05.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -6:05.2.0 core:copy (atom-text-editor.editor.is-focused)
     -6:00.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -6:00.1.0 core:paste (atom-text-editor.editor.is-focused)
     -5:58.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:51.7.0 tree-view:remove (li.file.entry.list-item.selected)
  3x -5:43 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:40.8.0 core:save (atom-text-editor.editor.is-focused)
  6x -4:57.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:54.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, vundefined
atom-html-preview, v0.1.19
color-picker, v2.1.1
file-icons, v1.7.13
highlight-selected, v0.11.2
linter, v1.11.4
linter-js-standard, v3.3.3
minimap, v4.24.3
pigments, v0.29.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
Probably a dirty install. Can't reproduce this.
