### ISSUE TITLE
Happiness

### ISSUE THREAD

**Issue by concon121** [ricardofbarros/linter-js-standard#119]
Basically reproduceable by enabling Happiness.

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.3.3
### Stack Trace

Uncaught Error: Implement me. Unknown stdin file type!

```
At node.js:747

Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:747:17)
    at Object.<anonymous> (C:\Users\conno\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\node_modules\get-stdin\index.js:2:20)
    at Module._compile (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\conno\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\bin\cmd.js:6:16)
    at Module._compile (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\conno\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\index.js:1:101)
    at Module._compile (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\conno\.atom\packages\linter-js-standard\node_modules\happiness\index.js:2:14)
    at Module._compile (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at requireWithLocalOverride (C:\Users\conno\.atom\packages\linter-js-standard\lib\utils\select-style.js:9:12)
    at C:\Users\conno\.atom\packages\linter-js-standard\lib\utils\select-style.js:18:16
    at exports.allowUnsafeNewFunction (C:\Users\conno\.atom\packages\linter-js-standard\node_modules\loophole\lib\loophole.js:25:14)
    at pickStandard (C:\Users\conno\.atom\packages\linter-js-standard\lib\utils\select-style.js:13:10)
    at getLinterFromStyle (C:\Users\conno\.atom\packages\linter-js-standard\lib\utils\select-style.js:85:14)
    at selectStyle (C:\Users\conno\.atom\packages\linter-js-standard\lib\utils\select-style.js:95:10)
    at Object.module.exports.__cacheTextEditor (C:\Users\conno\.atom\packages\linter-js-standard\lib\init.js:92:17)
    at storeSettings (C:\Users\conno\.atom\packages\linter-js-standard\lib\init.js:64:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:282:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:431:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\conno\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:658:19)
```
### Commands

```
     -1:06.4.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode)
     -1:06.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode)
  3x -0:53 window:toggle-dev-tools (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "linter-js-standard": {
    "checkStyleDevDependencies": false,
    "honorStyleSettings": true,
    "showEslintRules": true,
    "style": "happiness"
  }
}
```
### Installed Packages

``` coffee
# User
atom-maven, v0.12.1
atom-terminal-panel, v4.4.4
atom-xsltransform, v0.8.0
autocomplete-xml, v0.8.3
jshint, v1.8.5
linter, v1.11.4
linter-javac, v1.9.4
linter-js-standard, v3.3.3
linter-js-yaml, v1.2.5
linter-json-lint, v0.1.1
node-debugger, v1.7.0
vim-mode, v0.65.1
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by raistlinthewiz** [comment]
Same here:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.4.0


### Stack Trace

Uncaught Error: Implement me. Unknown stdin file type!

```
At node.js:747

Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:747:17)
    at Object.<anonymous> (C:\Users\shala\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\node_modules\get-stdin\index.js:2:20)
    at Module._compile (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\shala\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\bin\cmd.js:6:16)
    at Module._compile (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\shala\.atom\packages\linter-js-standard\node_modules\happiness\node_modules\standard-engine\index.js:1:101)
    at Module._compile (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\shala\.atom\packages\linter-js-standard\node_modules\happiness\index.js:2:14)
    at Module._compile (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at requireWithLocalOverride (C:\Users\shala\.atom\packages\linter-js-standard\lib\utils\select-style.js:9:12)
    at C:\Users\shala\.atom\packages\linter-js-standard\lib\utils\select-style.js:18:16
    at exports.allowUnsafeNewFunction (C:\Users\shala\.atom\packages\atom-beautify\node_modules\loophole\lib\loophole.js:25:14)
    at pickStandard (C:\Users\shala\.atom\packages\linter-js-standard\lib\utils\select-style.js:13:10)
    at getLinterFromStyle (C:\Users\shala\.atom\packages\linter-js-standard\lib\utils\select-style.js:85:14)
    at selectStyle (C:\Users\shala\.atom\packages\linter-js-standard\lib\utils\select-style.js:95:10)
    at Object.module.exports.__cacheTextEditor (C:\Users\shala\.atom\packages\linter-js-standard\lib\init.js:92:17)
    at storeSettings (C:\Users\shala\.atom\packages\linter-js-standard\lib\init.js:64:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:637:16)
    at atom-tabs.TabBarView.onClick (C:\Users\shala\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:688:17)
```

### Commands

```
     -1:55.2.0 core:copy (atom-text-editor.editor.is-focused)
     -1:52.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:50 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:49.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.6.0 tabs:close-other-tabs (li.texteditor.tab.sortable.active.right-clicked)
     -0:55.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:54.9.0 core:move-up (atom-text-editor.editor.is-focused)
 21x -0:54.5.0 core:select-left (atom-text-editor.editor.is-focused)
  2x -0:52.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:24.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:12 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "linter-js-standard": {
    "style": "happiness"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.15
linter, v1.11.14
linter-js-standard, v3.4.0
merge-conflicts, v1.4.4
minimap, v4.24.6
pigments, v0.29.2
standard-formatter, v2.0.1

# Dev
No dev packages
```

**Comment by pwagner** [comment]
I just upgraded to Atom 1.9.9 and the problem is still there, and it is not only affecting happiness. As soon as the style in the settings is changed to something other than "standard", Uncaught Errors keep popping up. I am using Windows 8.1  and linter-js-standard 3.4.1.

**Comment by entozoon** [comment]
Any news on this?
Same as above post on Windows 7

**Comment by entozoon** [comment]
Looks like there is a problem with process.stdin and Windows.
Commenting out line 2 of `\linter-js-standard\node_modules\get-stdin\index.js` will fix it temporarily.

Appears to be a known issue for other plugins such as:
https://github.com/Jam3/devtool/pull/44

**Comment by marvinroger** [comment]
Install Atom >= 1.12-beta1, fixed there!
