### ISSUE TITLE
every save is creating a new npm-debug.log file in atom 1.12.7, plugin version 3.7.0

### ISSUE THREAD

**Issue by kellyrmilligan** [ricardofbarros/linter-js-standard#157]
i'm not sure how to try out an earlier version, but just noticed this recently. when I run standard through command line, there is no npm debug. 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/kellymilligan/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/Users/kellymilligan/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'standard' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prestandard', 'standard', 'poststandard' ]
5 info lifecycle hapi-react-redux-example@1.0.0~prestandard: hapi-react-redux-example@1.0.0
6 silly lifecycle hapi-react-redux-example@1.0.0~prestandard: no script for prestandard, continuing
7 info lifecycle hapi-react-redux-example@1.0.0~standard: hapi-react-redux-example@1.0.0
8 verbose lifecycle hapi-react-redux-example@1.0.0~standard: unsafe-perm in lifecycle true
9 verbose lifecycle hapi-react-redux-example@1.0.0~standard: PATH: /Users/kellymilligan/.nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/kellymilligan/Documents/code/hapi-react-redux-example/node_modules/.bin:/Users/kellymilligan/.nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/kellymilligan/Documents/code/hapi-react-redux-example/node_modules/.bin:/Users/kellymilligan/.nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/kellymilligan/Documents/code/hapi-react-redux-example/node_modules/.bin:/Users/kellymilligan/.nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/kellymilligan/Documents/code/hapi-react-redux-example/node_modules/.bin:/Users/kellymilligan/.nvm/versions/node/v6.9.2/bin:/usr/local/sbin:/Users/kellymilligan/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle hapi-react-redux-example@1.0.0~standard: CWD: /Users/kellymilligan/Documents/code/hapi-react-redux-example
11 silly lifecycle hapi-react-redux-example@1.0.0~standard: Args: [ '-c', 'standard --fix --verbose | snazzy' ]
12 verbose stack Error: write EPIPE
12 verbose stack     at exports._errnoException (util.js:1022:11)
12 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
13 verbose cwd /Users/kellymilligan/Documents/code/hapi-react-redux-example
14 error Darwin 16.1.0
15 error argv "/Users/kellymilligan/.nvm/versions/node/v6.9.2/bin/node" "/Users/kellymilligan/.nvm/versions/node/v6.9.2/bin/npm" "run" "standard"
16 error node v6.9.2
17 error npm  v3.10.9
18 error code EPIPE
19 error errno EPIPE
20 error syscall write
21 error write EPIPE
22 error If you need help, you may report this error at:
22 error     <https://github.com/npm/npm/issues>
23 verbose exit [ 1, true ]
``

**Comment by kellyrmilligan** [comment]
I think it has something to do with that I am running npm scripts that are named standard as well?

I took out those to see, and it still generated logs, but they were empty.

**Comment by kellyrmilligan** [comment]
after making sure any processes with ports running being stopped, uninstalling node modules on my project, and reinstalling node modules and the plugin, it's not happening anymore. i'm guessing a process was hanging somewhere and it got stuck.

**Comment by ricardofbarros** [comment]
Hmm how strange :/ Black magic, oh well.
