### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by AugustinGrigorov** [ricardofbarros/linter-js-standard#158]
[Enter steps to reproduce below:]

1. Disable extension
2. Enable again

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Users/augstingrigorov/.atom/packages/linter-js-standard/lib/init.js:111

TypeError: Cannot read property 'style' of undefined
    at Object.__cacheTextEditor (/Users/augstingrigorov/.atom/packages/linter-js-standard/lib/init.js:111:18)
    at storeSettings (/Users/augstingrigorov/.atom/packages/linter-js-standard/lib/init.js:79:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

### Commands

```
     -2:29.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations.theme-one-dark-syntax.theme-atom-material-ui)
     -0:58.1.0 grammar-selector:show (input.hidden-input)
     -0:57 core:move-down (input.hidden-input)
     -0:56.8.0 core:confirm (input.hidden-input)
 16x -0:42.1.0 core:move-down (input.hidden-input)
  2x -0:37.4.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "linter-js-standard": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-ui, v1.3.9 (active)
atomic-chrome, v0.3.0 (active)
file-icons, v2.0.10 (active)
linter, v1.11.21 (active)
linter-js-standard, v3.8.0 (active)
nord-atom-syntax, v0.5.0 (inactive)
split-diff, v1.1.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by brandonb927** [comment]
I too an receiving this error, not entirely sure how to reproduce but it only seems to show up when editing files that contain JSX format.

**Comment by ricardofbarros** [comment]
Hey guys, this should because of the latest merge, some stuff changed, let me try to reproduce it.

**Comment by j-f1** [comment]
I can reproduce this, too:

1. Create a Markdown file
2. Add an image reference to it (<code>!\[](*path/to/image*)</code>)
3. Open Markdown Preview
4. Start dragging the image

**Comment by sdaitzman** [comment]
I am experiencing this same error.

**Comment by anandsuresh** [comment]
I experience this error everytime I do the following:

- Create a new file with the grammer set to JavaScript.
- Navigate away into a different tab (in my case, it was package.json)
- Edit the file (package.json) and save it.
- As soon as the file is saved, the error is triggered, with the result that the contents of the first file (the newly created file with JavaScript grammer) is lost. The entire buffer will unsaved changes is wiped out. (Thanksfully, I've been in the habit of saving progress regularly, so the loss was minimal).

**Comment by vinkla** [comment]
I've the exact same issue on macOS beta with Atom 1.14.3 and `linter-js-standard` 3.8.3.

**Comment by ricardofbarros** [comment]
Hey guys ( @brandonb927 , @dcalhoun , @j-f1 , @sdaitzman , @anandsuresh and @vinkla )

I was able to reproduce all bugs (thanks for the detailed info btw), so I've just released a new version that should fix this issues. Care to test?

Thanks
