### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by mospired** [ricardofbarros/linter-js-standard#226]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.1
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package 6.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:21:9)
    at settings.style.lintText (/packages/linter-js-standard/lib/linter-js-standard.js:25:17)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  2x -1:06.8.0 core:move-down (input.hidden-input)
     -1:06.0 core:move-up (input.hidden-input)
  2x -1:05.7.0 core:move-left (input.hidden-input)
     -1:05.2.0 core:backspace (input.hidden-input)
     -1:04.0 core:save (input.hidden-input)
     -0:59.1.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:58.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -0:57.9.0 core:backspace (input.hidden-input)
     -0:53.3.0 core:confirm (input.hidden-input)
     -0:41.7.0 tree-view:move (span.name.icon.icon-file-text)
     -0:41 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -0:40.7.0 core:move-left (input.hidden-input)
  4x -0:39.4.0 core:select-left (input.hidden-input)
     -0:34.8.0 core:confirm (input.hidden-input)
  6x -0:15.7.0 find-and-replace:select-next (input.hidden-input)
  2x -0:10.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
compare-files 0.8.1 
github-atom-light-syntax 0.5.0 
intentions 1.1.5 
language-babel 2.85.0 
language-dotenv 1.2.0 
language-liquid 0.7.0 
language-nunjucks 4.2.1 
linter 2.2.0 
linter-js-standard 6.1.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
```

**Comment by sonicdoe** [comment]
Thanks for reporting this issue. What kind of file did you have open when you were trying to save? Was it an ordinary local file?

**Comment by sonicdoe** [comment]
I’m still not entirely sure under which circumstances this happens, however, the underlying cause should now be fixed with https://github.com/ricardofbarros/linter-js-standard/commit/922125f13e9226803d0e6231e635541b142b7ef6 in linter-js-standard v6.1.1.
