### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by JurrianK** [ricardofbarros/linter-js-standard#61]
[Enter steps to reproduce below:]

1. install using the package handler
2. ???

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At C:\Users\Jurrian\.atom\packages\linter-js-standard\lib\init.js:58

TypeError: Cannot read property 'scopeName' of undefined
  at storeSettings (C:\Users\Jurrian\.atom\packages\linter-js-standard\lib\init.js:58:39)
  at Emitter.module.exports.Emitter.emit (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:314:21)
  at tabs-tab.<anonymous> (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Jurrian\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:52.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 emmet:merge-lines (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
autoclose-html, v0.19.0
emmet, v2.3.13
linter, v1.8.1
linter-htmlhint, v0.1.1
linter-js-standard, v3.2.1
markdown-preview-plus, v2.2.2
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
Is this still happening after a re-install?

**Comment by JurrianK** [comment]
Hello Mr Barros,

It seems like a reinstall indeed did the trick, I just installed again and
messed around for a bit and no errors like the last time were given.

Thank you for your input on this problem.

Kind regards,

Jurrian

2015-10-23 14:56 GMT+02:00 Ricardo Barros <notifications@github.com>:

**Comment by ricardofbarros** [comment]
Okay, glad it got solved :+1:

**Comment by andradei** [comment]
I'm getting the same error again. But under a different circumstance.

When I update a _any_ package (like the one on the screenshot, for example) and try to see the CHANGELOG tab, I can't, and trying to close that tab generates the error on the screenshot.

<img width="1440" alt="screen shot 2016-01-14 at 10 23 09" src="https://cloud.githubusercontent.com/assets/2653546/12331913/f21fb46c-baa8-11e5-811a-851bb50e0225.png">

If I delete _linter-js-standard_ the error goes away.

Error log:

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.2.1


### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At ~/.atom/packages/linter-js-standard/lib/init.js:58

TypeError: Cannot read property 'scopeName' of undefined
    at storeSettings (~/.atom/packages/linter-js-standard/lib/init.js:58:39)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:316:21)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:279:21)
    at atom-workspace.commandRegistry.add.pane:show-previous-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:14:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -8:00.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -7:33 settings-view:open (atom-pane.pane.active)
     -4:22.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-slime.theme-nucleus-dark-ui)
  4x -2:26.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:12.1.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -2:10.5.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:45.2.0 pane:show-next-item (button.btn.btn-default.icon.icon-squirrel)
     -0:44.6.0 pane:show-previous-item (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autohide-tree-view",
      "omnisharp-atom",
      "auto-detect-indentation"
    ],
    "projectHome": "/Users/sargas/Documents/code",
    "themes": [
      "nucleus-dark-ui",
      "slime"
    ]
  },
  "linter-js-standard": {
    "honorStyleSettings": true,
    "lintMarkdownFiles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
atom-yeoman, v0.3.15
color-picker, v2.0.14
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
file-types, v0.5.1
go-plus, v3.5.2
highlight-selected, v0.11.1
hyperclick, v0.0.35
indent-guide-improved, v1.4.5
js-hyperclick, v1.4.1
json-schema, v0.1.15
language-gitignore, v0.2.0
language-groovy, v0.5.0
language-rust, v0.4.5
linter, v1.11.3
linter-js-standard, v3.2.1
linter-rust, v0.3.0
minimap, v4.19.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
nucleus-dark-ui, v0.7.3
pigments, v0.19.6
project-manager, v2.7.3
racer, v0.17.2
slime, v1.4.0
tab-control, v0.6.9
tabs-to-spaces, v1.0.1
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by sorear** [comment]
I'm also seeing @andradei 's error.  I might attempt a PR in a few days.

**Comment by andradei** [comment]
This error still exists in Atom 1.6.2
apm  1.6.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.1

Any plans to fix it?

**Comment by ricardofbarros** [comment]
Hello, I'm also getting this error, I'll run quick investigation and get back at you guys. Thanks

**Comment by ricardofbarros** [comment]
The problem is that `editor.getGrammar()` sometimes returns null and that's why this happens.

You can check this atom issue in further detail [here.](https://github.com/atom/atom/issues/6235).

I will push a patch to fix this problem of `.getGrammar()` returning an object or null. 

`3.3.2` will fix this. Thanks
