### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'replace' of undefined" when attempting to close tab

### ISSUE THREAD

**Issue by shawninder** [ricardofbarros/linter-js-standard#62]
Repro:

1. Unknown (this happens once in a while, not systematically)
2. Try closing a tab
3. Observe the tab doesn't close and an error notification appears

Fix by triggering `Window:reload` and trying again

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/shawn/.atom/packages/linter-js-standard/lib/utils/style-settings.js:20

TypeError: Cannot read property 'replace' of undefined
  at Object.checkStyleSettings (/Users/shawn/.atom/packages/linter-js-standard/lib/utils/style-settings.js:20:34)
  at Object.module.exports.__cacheTextEditor (/Users/shawn/.atom/packages/linter-js-standard/lib/init.js:100:21)
  at storeSettings (/Users/shawn/.atom/packages/linter-js-standard/lib/init.js:63:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:308:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:279:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:396:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:466:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:443:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  2x -3:17.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:12.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:10.5.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -3:07.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:07.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -3:06.6.0 script:run (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -2:56.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:52.9.0 script:run (atom-text-editor.editor.is-focused)
     -2:34.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:23.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 core:close (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "welcome",
      "timecop",
      "symbols-view",
      "styleguide",
      "release-notes",
      "metrics",
      "bookmarks"
    ]
  },
  "linter-js-standard": {
    "honorStyleSettings": true
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.10
coffee-compile, v0.19.2
docs-snippets, v0.8.0
editorconfig, v1.2.0
emmet, v2.3.13
highlight-selected, v0.10.1
language-swift, v0.4.0
linter, v1.8.1
linter-htmlhint, v0.1.1
linter-js-standard, v3.2.1
linter-package-json-validator, v0.2.2
pretty-json, v0.4.1
script, v3.0.1
standard-formatter, v1.1.3
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
Hmm as isn't a systematic error it will be hard to replicate, but I will try, thanks @shawninder

**Comment by shaungrady** [comment]
I'm able to reliably replicate.

1. Create new, unsaved file
2. Type in some JS, such as `{}`, and set the syntax to `JavaScript`
3. Switch to a different tab, then switch back to the new file. Poof, error.

**Comment by despairblue** [comment]
Happens also with the current beta (1.3.0-beta6).

**Comment by despairblue** [comment]
Happens because [`getPath`](https://github.com/ricardofbarros/linter-js-standard/blob/master/lib/init.js#L91) returns undefined for a file that has not been saved.

**Comment by sbromberger** [comment]
This is still happening (v 3.2.1).

**Comment by ricardofbarros** [comment]
Merged a PR from @thtliife, should be fixed on the latest release.
