### ISSUE TITLE
Can not open packages changelog with linter-js enabled

### ISSUE THREAD

**Issue by ngrande** [ricardofbarros/linter-js-standard#87]
I am unable to view changelogs from packages in my atom editor while the linter-js-standard is enabled.
_I reviewed the other open issues but was not sure if this issue would fit somewhere else so i opened this new one here._

i get the following error:
```
...\.atom\packages\linter-js-standard\lib\init.js:58 Uncaught (in promise) TypeError: Cannot read property 'scopeName' of undefined
    at storeSettings (C:\Users\ngrande\.atom\packages\linter-js-standard\lib\init.js:58:39)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:316:21)
    at C:\Users\ngrande\AppData\Local\atom\app-1.4.3\resources\app.asar\src\workspace.js:505:18
```

this issue does not appear when editing a .md file (opened via the open file dialog or at startup).

**Comment by ricardofbarros** [comment]
Hello @ngrande, this is fixed as now of `3.3.2`. This is originally a bug from atom, you can get more info of #61.
