### ISSUE TITLE
module.js:338 Error

### ISSUE THREAD

**Issue by alice-em** [ricardofbarros/linter-js-standard#92]
[Enter steps to reproduce below:]
1. Create new file 'index.js' in Atom (for a Node project)
2. Go to 'index.js' via side Folder Projects
3. Uncaught Error: module.js:338

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v3.2.1
### Stack Trace

Uncaught Error: Cannot find module 'clone'

```
At module.js:338

Error: Cannot find module 'clone'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alice_em/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/node_modules/defaults/index.js:1:92)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alice_em/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/bin/cmd.js:3:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alice_em/.atom/packages/linter-js-standard/node_modules/standard/node_modules/standard-engine/index.js:1:101)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alice_em/.atom/packages/linter-js-standard/node_modules/standard/index.js:2:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Users/alice_em/.atom/packages/linter-js-standard/lib/utils/select-style.js:7:16
    at exports.allowUnsafeNewFunction (/Users/alice_em/.atom/packages/linter-js-standard/node_modules/loophole/lib/loophole.js:25:14)
    at pickStandard (/Users/alice_em/.atom/packages/linter-js-standard/lib/utils/select-style.js:4:10)
    at selectStyle (/Users/alice_em/.atom/packages/linter-js-standard/lib/utils/select-style.js:58:14)
    at Object.module.exports.__cacheTextEditor (/Users/alice_em/.atom/packages/linter-js-standard/lib/init.js:91:17)
    at storeSettings (/Users/alice_em/.atom/packages/linter-js-standard/lib/init.js:63:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:312:19)
    at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:267:21)
    at atom-workspace.commandRegistry.add.pane:show-next-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:11:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:10.9.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:05.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:11.6.0 pane:show-next-item (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "git-plus",
      "merge-conflicts"
    ],
    "projectHome": "/Documents/Git",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.22
autoclose-html, v0.21.0
color-picker, v2.1.1
emmet, v2.4.1
file-icons, v1.6.14
jQuery, v1.2.1
jquery-snippets, v11.0.0
linter, v1.11.3
linter-js-standard, v3.2.1
menu-manager, v0.4.4
minimap, v4.19.0
neon-cursor, v1.4.0
neon-selection, v0.3.2
php-cs-fixer, v2.5.6
react, v0.14.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
Probably a dirty install. Can't reproduce.
